# Generated by Django 6.1.1 on 2026-10-08 08:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text='Optional. Enter your first name.', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Optional. Enter your last name.', max_length=150, verbose_name='last name')),
                ('age', models.PositiveSmallIntegerField(help_text='Enter your age.', verbose_name='age')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Required. Enter your phone number.', max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('driver', 'Driver')], default='client', help_text='Required. Select the role of the user (Admin, Client, or Driver).', max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('suspended', 'Suspended'), ('pending', 'Pending'), ('verified', 'Verified')], default='pending', help_text='Required. Select the status of the user (Suspended or Verified or Pending).', max_length=20, verbose_name='status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('can_suspend_user', 'Can suspend user'), ('can_verify_user', 'Can verify user'), ('can_change_user_role', 'Can change user role')],
            },
        ),
    ]
