# Generated by Django 6.1.1 on 2026-10-01 19:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('home_address', models.TextField()),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('van', 'Cargo Van'), ('rigid_truck', 'Rigid Truck'), ('articulated_truck', 'Articulated Truck')], max_length=30)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, max_length=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
    ]
