# Generated by Django 6.1.1 on 2026-10-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_name',
        ),
    ]
